// Generated by Selenium IDE
package com.masteringselenium;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

public class BasicIT {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void nothing() {
        driver.get("https://www.google.com/");
        driver.manage().window().setSize(new Dimension(1188, 1087));
        driver.findElement(By.name("q")).click();
        driver.findElement(By.name("q")).sendKeys("bonusfinder");
        driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
        driver.findElement(By.cssSelector("div:nth-child(3) > .tF2Cxc .LC20lb")).click();
        WebDriverWait wait = new WebDriverWait(driver,20);
        wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".current-lang > .no-lazyload")));
        driver.findElement(By.cssSelector(".current-lang > .no-lazyload")).click();
        WebDriverWait wait2 = new WebDriverWait(driver,20);
        wait2.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".en_US .lazyloaded")));
        driver.findElement(By.cssSelector(".en_US .lazyloaded")).click();
        driver.findElement(By.cssSelector(".search-row-dropdown .bf-search-top")).click();
        driver.findElement(By.cssSelector(".active .bf-search-item:nth-child(3)")).click();
        driver.findElement(By.cssSelector(".search-row-deposit .bf-search-top")).click();
        driver.findElement(By.cssSelector(".active .bf-search-item:nth-child(5) > div")).click();
        driver.findElement(By.cssSelector(".search-btn > div")).click();
        WebDriverWait wait3 = new WebDriverWait(driver,20);
        wait3.until(ExpectedConditions.elementToBeClickable(By.linkText("Scores Casino")));
        driver.findElement(By.linkText("Scores Casino")).click();
        driver.manage().timeouts().implicitlyWait(0, TimeUnit.SECONDS);

        driver.close();
    }
}
